services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bubble_pop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    image: bubblepop:latest
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: bubble_pop
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

volumes:
  postgres_data:
