CREATE TABLE IF NOT EXISTS scores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL CHECK (char_length(player_name) BETWEEN 1 AND 100),
    score INTEGER NOT NULL CHECK (score >= 0),
    difficulty TEXT NOT NULL CHECK (difficulty IN ('Легко', 'Средний', 'Сложно')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_scores_score ON scores(score DESC);
CREATE INDEX IF NOT EXISTS idx_scores_created_at ON scores(created_at DESC);
